### PR TITLE
WIndows compatibility

### PR DESCRIPTION
**Pull request by nvdweem**
I added the required steps and libraries/downloads in the readme file. It should all still work on Linux but I havent tested it.

### CODE REVIEW

**Comment by nahojkap** [comment]
I pulled this in and it works fine (only a minor fix in the pom to get it to build).  One question however - in the JahSpotify.c, you changed the length of the array used in the toHexString function.  The loop however only produces 40 characters still (it loops 20 times).  What was the intention with the increased loop size?

**Comment by nvdweem** [comment]
Your right, I probably should have changed the loop condition too. I found that this request:
http://localhost:8080/jahspotify/ui/media/spotify:user:merlin-vl:playlist:4SULEfgynOOvejllapqbVt
produces a call to the toHexString function with a hash of: A99AEDA1D4FE08C0561A4DAB79DCFB2B47A4BCA7A7 (42 tokens) which resulted in a silent crash of Jah'Spotify. Changing the size of the hash and finalhash fixed the crash, but probably didn't produce a correct result.

**Comment by nahojkap** [comment]
Interesting that the length changes - it is only used to create hex versions of image IDs - which by the API definition is sp_image_create (sp_session *session, const byte image_id[20]) ... something is a little fishy :)

**Comment by nahojkap** [comment]
And another concern now would be that the code will be using up to 9 bytes of 'random' memory - since we don't know the actual length of the input (which I assumed was always 20).  Did you happen to see what the crash was when the ID was 21 bytes long?

**Comment by nvdweem** [comment]
Not really, it didn't give an access violation, it just crashed silently. You should be able to reproduce it with the playlist I provided.

**Comment by nahojkap** [comment]
I tried the playlist but it never loads for some reason ... this is somebody elses playlist right?

**Comment by nvdweem** [comment]
It might not be loading because of the error ;). I'll try to find out which track causes the problem when I get time.

**Comment by nahojkap** [comment]
no, it was actually waiting for spotify to complete the loading :)  Thanks for taking a look

**Comment by nvdweem** [comment]
It appears to be the artist Bruno Mars. If I create a playlist of my own and add a song of him to it then the playlist won't load. The debug message is 'Populating artist browse instance' and it crashes after about a minute or so.

**Comment by nahojkap** [comment]
any particular song?  or any?  Cause I tried and not seeing an issue ... quite strange :)

**Comment by nvdweem** [comment]
The problem here is with the artistbrowse function, so it shouldn't be tied to any track.

Perhaps we are going about this the wrong way. I can imagine that its just that the strcopy function is used incorrectly:

```
The strcpy() function shall copy the string pointed to by s2 (including the terminating null byte) ...
```

If the byte[20] doesn't end with a null byte then the strcpy will just keep copying until it finds one, right? Is there any point in putting the hash in a char[40], and not straight into the char *?
The last commit also seems to produce a working application.

**Comment by nahojkap** [comment]
I noticed this and increased the copied buffer by 1 byte (assume this is what you meant by the last commit?).  Could be the old code wrote 20 + 1?  Anyway, if this works better, then this is the path forward. And it was my initial ignorance of C that caused me to use the intermediate buffer - will fix this too :)

**Comment by nvdweem** [comment]
The old code wrote 20 bytes (40 chars) in the hash. The method signature of the strcopy method is 'char *strcpy(char *restrict s1, const char *restrict s2);', so it will use the array as a char pointer and it will read from the start until the first null byte which could be later then the first 40 chars (depending on the random piece of memory after the array).

I think there were 2 solutions:
- The solution I committed, increase the length by 1 and terminating the string with a null character to make it a valid string and then use it in the methods which require the null char.
- Not using it as a string but as a character array, this would mean not using strcopy and not using strcat in populateJArtistInstanceFromArtistBrowse

But of course, I could be wrong :) I really don't know very much about C, I'm also not sure why this went wrong with specifically this playlist because it probably had more to do with random parts of memory.

**Pull request merged**
